apiVersion: batch/v1
kind: Job
metadata:
  name: job-example
  namespace: sdp-demo
  annotations:
    k8s.appgate.com/sdp-injector.client-version: "test"
spec:
  template:
    spec:
      containers:
        - name: sleep-and-complete
          image: localhost:5000/example-job:test
          imagePullPolicy: Always
          securityContext:
            runAsUser: 1001
      restartPolicy: Never
  backoffLimit: 1
