[package]
name = "sdp-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdp-test-macros = { path = "../sdp-test-macros" }

serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
kube = { version = "0.74.0", default-features = false, features = ["admission", "rustls-tls", "derive", "client", "runtime"] }
k8s-openapi = { version = "0.15.0", default-features = false, features = ["v1_24"] }
schemars = "0.8.10"
uuid = { version = "1.1.2", features = ["v4", "fast-rng"] }
reqwest = { version = "0.11", features = ["hyper-rustls", "json"] }
http = "0.2"
log = "0.4.0"
json-patch = "*"
