apiVersion: v2
name: sdp-k8s-injector-crd
description: Helm chart for SDP Kubernetes Injector CRD

type: application

# Chart version should remain consistent with ../chart/Chart.yaml
version: "1.1.0"

# Chart appVersion should be the same as ../chart/Chart.yaml
appVersion: "1.1.0"
