#!/usr/bin/env sh

function decho () {
    echo $(date +"%b %d %X") $@
}

# NOTE: stdin reads from the socat socket.
read cli
decho "Got new event from workload container: $cli"
case $cli in
     "stop")
         kill -9 1
         ;;
     *)
         ;;
esac
