#!/usr/bin/env sh

if [ -z "$REVISION" ] || [ "$REVISION" = 0 ]
then
  exec /opt/appgate/appgate-driver \
    -d \
    -p /var/run/sdp-driver/.driver.sock \
    --container \
    -l /var/log/appgate/driver.log \
    --varrun /var/run/sdp-driver
else
  /opt/appgate/appgate-driver \
    -d \
    -p /var/run/sdp-driver/.driver.sock \
    --container \
    -l /var/log/appgate/driver.log \
    --varrun /var/run/sdp-driver&
  exec /opt/appgate/wait-for-stop /var/run/sdp-driver/stop.sock
fi
