#!/usr/bin/env sh

/opt/appgate/appgate-driver \
  -d \
  -p /var/run/sdp-driver/.driver.sock \
  --container -l /var/log/appgate/driver.log \
  --varrun /var/run/sdp-driver&

/opt/appgate/wait-for-stop /var/run/sdp-driver/stop.sock
