#!/usr/bin/env sh

if [ -n "$CLIENT_DEVICE_ID" ]; then
    echo "Using custom device-id: $CLIENT_DEVICE_ID"
    echo "$CLIENT_DEVICE_ID" | sed 's|-||g' > /etc/machine-id
fi

cat > /etc/appgate.conf <<EOF
[Settings]
LogLevel = $CLIENT_LOGLEVEL
[Credentials]
ControllerUrl = $CLIENT_CONTROLLER_URL
Username = $CLIENT_USERNAME
Password = $CLIENT_PASSWORD
EOF
echo Running service
exec /opt/appgate/service/appgateservice -t /var/run/appgate/.driver.sock --service
