#!/usr/bin/env sh

WATCHER_SOCKET=/run/run/sdp-dnsmasq/sdp-service-watcher.sock

# Backwards compatibility for alpha version
if [ -n "$CLIENT_LOGLEVEL" ]; then
    APPGATE_LOGLEVEL=$CLIENT_LOGLEVEL
fi

if [ -n "$CLIENT_PROFILE_URL" ]; then
    APPGATE_PROFILE_URL=$CLIENT_PROFILE_URL
fi

if [ -n "$CLIENT_USERNAME" ]; then
    APPGATE_USERNAME=$CLIENT_USERNAME
fi

if [ -n "$CLIENT_PASSWORD" ]; then
    APPGATE_PASSWORD=$CLIENT_PASSWORD
fi

if [ -n "$CLIENT_DEVICE_ID" ]; then
    APPGATE_DEVICE_ID=$CLIENT_DEVICE_ID
fi

# Set Device ID into /etc/machine-id
if [ -n "$APPGATE_DEVICE_ID" ]; then
    echo "Device ID: $APPGATE_DEVICE_ID"
    echo "$APPGATE_DEVICE_ID" | sed 's|-||g' > /etc/machine-id
fi

cat > /sdp-service/appgate.conf <<EOF
[Settings]
LogLevel = $APPGATE_LOGLEVEL
[Credentials]
ControllerUrl = $APPGATE_PROFILE_URL
Username = $APPGATE_USERNAME
Password = $APPGATE_PASSWORD
EOF

/opt/appgate/service/appgateservice --config /sdp-service/appgate.conf \
    --tun /var/run/sdp-driver/.driver.sock \
    --service&
/opt/appgate/sdp-service-watcher&
/opt/appgate/wait-for-stop /var/run/sdp-service/stop.sock
