#!/usr/bin/env sh

function decho () {
    echo $(date +"%b %d %X") $@
}

PID=$1

# NOTE: stdin reads from the socat socket.
read cli
decho "Got new event from workload container: $cli"
case $cli in
     "stop")
         kill -9 $PID
         ;;
     "status")
         /opt/appgate/sdp-service-probe && echo "ready" || echo "waiting"
         ;;
     *)
         ;;
esac
