apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "sdp-injector.injector-certificate" . }}
  namespace: {{ include "sdp-injector.namespace" . }}
spec:
  secretName: {{ include "sdp-injector.injector-secret" . }}
  dnsNames:
    - {{ include "sdp-injector.fullname" . }}
    - {{ include "sdp-injector.fullname" . }}.{{ include "sdp-injector.namespace" . }}
    - {{ include "sdp-injector.fullname" . }}.{{ include "sdp-injector.namespace" . }}.svc
    - {{ include "sdp-injector.fullname" . }}.{{ include "sdp-injector.namespace" . }}.svc.cluster.local
  issuerRef:
    name: {{ include "sdp-injector.injector-issuer" . }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "sdp-injector.injector-issuer" . }}
  namespace: {{ include "sdp-injector.namespace" . }}
spec:
  selfSigned: {}
