apiVersion: v1
kind: ConfigMap
metadata:
  name: sdp-injector-client-config
  namespace: {{ include "sdp-injector.namespace" . }}
  labels:
  {{- include "sdp-injector.labels" . | nindent 4 }}
data:
  appgate-log-level: {{ .Values.sdp.injector.logLevel }}
  client-controller-url: {{ required ".Values.sdp.host is required" .Values.sdp.host }}
