apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sdp-injector.sidecar-config" . }}
  namespace: {{ include "sdp-injector.namespace" . }}
  labels:
  {{- include "sdp-injector.labels" . | nindent 4 }}
data:
  sdp-sidecars.json: |-
    {
      "initContainers": [
        {
          "name": "sdp-init-container-0",
          "image": "busybox",
          "imagePullPolicy": "IfNotPresent",
          "securityContext": {
            "allowPrivilegeEscalation": false,
            "runAsUser": 0
          },
          "command" : [
            "sh",
            "-c",
            "echo \"nameserver $K8S_DNS_SERVICE\nsearch $K8S_DNS_SEARCHES\"> /etc/resolv.conf"
          ]
        },
        {
          "name": "sdp-init-container-f",
          "image": "busybox",
          "imagePullPolicy": "IfNotPresent",
          "securityContext": {
            "allowPrivilegeEscalation": false,
            "runAsUser": 0
          },
          "command" : [
            "sh",
            "-c",
            "echo \"nameserver 127.0.0.1\nsearch $K8S_DNS_SEARCHES\"> /etc/resolv.conf"
          ]
        }
      ],
      "containers": [
        {
          "name": "sdp-service",
          "image": "{{ default .Values.global.image.repository .Values.sdp.headlessService.image.repository }}/sdp-headless-service:{{ default .Values.sdp.clientVersion  .Values.sdp.headlessService.image.tag }}",
          "imagePullPolicy": "{{.Values.sdp.headlessService.image.pullPolicy}}",
          "securityContext": {
            "runAsGroup": 102,
            "runAsUser":103,
            "runAsNonRoot": true
          },
          "resources": {},
          "terminationMessagePath": "/dev/termination-log",
          "terminationMessagePolicy": "File",
          "volumeMounts": [
            {
              "mountPath": "/var/run/sdp-dnsmasq",
              "name": "run-sdp-dnsmasq"
            },
            {
              "mountPath": "/var/run/sdp-driver",
              "name": "run-sdp-driver"
            },
            {
              "mountPath": "/var/log/appgate",
              "name": "sdp-driver-logs"
            },
            {
              "mountPath": "/etc/pod-info",
              "name": "pod-info"
            }
          ],
          "readinessProbe": {
            "exec": {
              "command": [
                "/opt/appgate/sdp-service-probe"
              ]
            },
            "initialDelaySeconds": 10
          }
        },
        {
          "name": "sdp-driver",
          "image": "{{ default .Values.global.image.repository .Values.sdp.headlessDriver.image.repository }}/sdp-headless-driver:{{ default .Values.sdp.clientVersion .Values.sdp.headlessDriver.image.tag }}",
          "imagePullPolicy": "{{.Values.sdp.headlessDriver.image.pullPolicy}}",
          "securityContext": {
            "runAsGroup": 101,
            "runAsUser": 103,
            "runAsNonRoot": true,
            "fsGroup": 101,
            "capabilities": {
              "add": [
                  "NET_ADMIN",
                  "NET_BIND_SERVICE"
              ]
            }
          },
          "volumeMounts": [
            {
              "mountPath": "/var/run/sdp-driver",
              "name": "run-sdp-driver"
            },
            {
              "mountPath": "/var/run/sdp-dnsmasq",
              "name": "run-sdp-dnsmasq"
            },
            {
              "mountPath": "/var/log/appgate",
              "name": "sdp-driver-logs"
            },
            {
              "mountPath": "/dev/net/tun",
              "name": "tun-device"
            }
          ]
        },
        {
          "name": "sdp-dnsmasq",
          "image": "{{ default .Values.global.image.repository .Values.sdp.dnsmasq.image.repository }}/sdp-dnsmasq:{{ default .Values.sdp.clientVersion .Values.sdp.dnsmasq.image.tag }}",
          "imagePullPolicy": "{{.Values.sdp.dnsmasq.image.pullPolicy}}",
          "securityContext": {
            "runAsGroup": 101,
            "runAsUser": 100,
            "runAsNonRoot": true
          },
          "volumeMounts": [
            {
              "mountPath": "/var/run/sdp-dnsmasq",
              "name": "run-sdp-dnsmasq"
            }
          ],
          "command": [
              "/sdp-dnsmasq/sdp-dnsmasq"
          ]
        }
      ],
      "dnsConfig": {
        "searches": "{{ join " " .Values.sdp.dnsmasq.dnsConfig.searches}}"
      },
      "volumes": [
        {
          "mountPath": "/var/run/sdp-driver",
          "name": "run-sdp-driver"
        },
        {
          "mountPath": "/var/log/appgate",
          "name": "sdp-driver-logs"
        },
        {
          "mountPath": "/var/run/sdp-dnsmasq",
          "name": "run-sdp-dnsmasq"
        },
        {
          "hostPath": {
            "path": "/dev/net/tun"
          },
          "name": "tun-device"
        },
        {
          "name": "pod-info",
          "downwardAPI": {
            "items": [
              {
                "path": "labels",
                "fieldRef": {
                  "fieldPath": "metadata.labels"
                }
              },
              {
                "path": "annotations",
                "fieldRef": {
                  "fieldPath": "metadata.annotations"
                }
              }
            ]
          }
        }
      ]
    }
