apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sdp-injector.fullname" . }}-log
  namespace: {{ include "sdp-injector.namespace" . }}
  labels:
  {{- include "sdp-injector.labels" . | nindent 4 }}
data:
  sdp-identity-service-log4rs.yaml: |
    refresh_rate: 30 seconds
    appenders:
      stdout:
        kind: console
        encoder:
          pattern: "{h({d(%Y-%m-%d %H:%M:%S %Z)} {l} {m}{n})}"
      file:
        kind: file
        path: "sdp-identity-service.log"
        encoder:
          pattern: "{d(%Y-%m-%d %H:%M:%S %Z)} {l} {m}{n}"
    root:
      level: {{ .Values.sdp.identityService.logLevel }}
      appenders:
        - stdout
        - file

  sdp-injector-log4rs.yaml: |
    refresh_rate: 30 seconds
    appenders:
      stdout:
        kind: console
        encoder:
          pattern: "{h({d(%Y-%m-%d %H:%M:%S %Z)} {l} {m}{n})}"
      file:
        kind: file
        path: "sdp-injector.log"
        encoder:
          pattern: "{d(%Y-%m-%d %H:%M:%S %Z)} {l} {m}{n}"
    root:
      level: {{ .Values.sdp.injector.logLevel }}
      appenders:
        - stdout
        - file
