apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "sdp-k8s-client.name" . }}-preinstall
  namespace: {{ include "sdp-k8s-client.namespace" . }}
  labels:
    {{- include "sdp-k8s-client.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "delete", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "sdp-k8s-client.name" . }}-preinstall
  namespace: {{ include "sdp-k8s-client.namespace" . }}
  labels:
    {{- include "sdp-k8s-client.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
subjects:
  - kind: ServiceAccount
    name: {{ include "sdp-k8s-client.serviceAccountName" . }}-hooks
    namespace: {{ include "sdp-k8s-client.namespace" . }}
roleRef:
  kind: Role
  name: {{ include "sdp-k8s-client.name" . }}-preinstall
  apiGroup: rbac.authorization.k8s.io