apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sdp-k8s-client.fullname" . }}-device-id-service
  namespace: {{ include "sdp-k8s-client.namespace" . }}
  labels:
  {{- include "sdp-k8s-client.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.sdp.deviceIdService.replica }}
  selector:
    matchLabels:
      {{- include "sdp-k8s-client.selectorLabels" . | nindent 6 }}-device-id-service
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sdp-k8s-client.selectorLabels" . | nindent 8 }}-device-id-service
    spec:
      {{- with .Values.global.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "sdp-k8s-client.serviceAccountName" .}}
      containers:
        - name: {{ .Chart.Name }}-device-id-service
          env:
            - name: RUST_LOG
              value: {{ .Values.sdp.deviceIdService.logLevel | default "info" }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ default .Values.global.image.repository .Values.sdp.deviceIdService.image.repository }}/sdp-device-id-service:{{ default (include "sdp-k8s-client.defaultTag" .) .Values.sdp.deviceIdService.image.tag }}"
          imagePullPolicy: {{ default .Values.global.image.pullPolicy .Values.sdp.deviceIdService.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sdp-k8s-client.fullname" . }}-device-id-service
  namespace: {{ include "sdp-k8s-client.namespace" . }}
  labels:
    {{- include "sdp-k8s-client.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8443
      name: https
  selector:
    {{- include "sdp-k8s-client.selectorLabels" . | nindent 4 }}-device-id-service
