apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sdp-k8s-client.serviceAccountName" .}}
  namespace: {{ include "sdp-k8s-client.namespace" . }}
  labels:
  {{- include "sdp-k8s-client.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
