[package]
name = "sdp-device-id-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdp-common = {path = "../sdp-common"}

clap = { version = "3.2.17", features = ["derive"] }
tokio = { version = "~1.18", features = ["rt", "macros", "rt-multi-thread"] }
env_logger = "0.7.1"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
kube = { version = "0.73.1", default-features = false, features = ["admission", "rustls-tls", "derive", "client", "runtime"] }

