[package]
name = "sdp-device-id-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdp-common = {path = "../sdp-common"}
sdp-macros = { path = "../sdp-macros" }
sdp-proc-macros = { path = "../sdp-proc-macros" }
sdp-test-macros = { path = "../sdp-test-macros" }

clap = { version = "3.2.17", features = ["derive"] }
tokio = { version = "~1.18", features = ["rt", "macros", "rt-multi-thread"] }
env_logger = "0.7.1"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
kube = { version = "0.74", default-features = false, features = ["admission", "rustls-tls", "derive", "client", "runtime"] }
k8s-openapi = { version = "0.15.0", default-features = false, features = ["v1_20"] }
schemars = "0.8.10"
uuid = { version = "1.1.2", features = ["v4", "fast-rng"] }
log = "0.4.0"
futures = "^0.3.0"

