name: Build and Push Injector Images

on:
  workflow_call:
    inputs:
      push:
        required: true
        type: boolean

jobs:
  docker-build-injector:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Read package version
        id: package-version
        run: |
          version=$(cargo metadata --format-version 1 | jq --raw-output '.packages[] | select(.name == "sdp-injector") | .version')
          echo VERSION="${version}" >> $GITHUB_ENV

      - name: Get build profile
        id: build-profile
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo PROFILE="release" >> $GITHUB_ENV
          else
            echo PROFILE="debug" >> $GITHUB_ENV
          fi

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        if: ${{ inputs.push }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get commit short hash
        run: echo GIT_COMMIT=$(git rev-parse --short "$GITHUB_SHA") >> $GITHUB_ENV

      - name: Build cached layer
        uses: docker/build-push-action@v6
        with:
          build-args: PROFILE=${{ env.PROFILE }}
          context: .
          file: docker/sdp-k8s-injector-Dockerfile
          push: false
          tags: sdp-k8s-injector-build:latest

      - name: Build sdp-identity-service
        uses: docker/build-push-action@v6
        with:
          build-args: PROFILE=${{ env.PROFILE }}
          context: .
          file: sdp-identity-service/Dockerfile
          push: ${{ inputs.push }}
          tags: |
            ghcr.io/${{ github.repository }}/sdp-identity-service:${{ env.VERSION }}
            ghcr.io/${{ github.repository }}/sdp-identity-service:${{ env.VERSION }}-${{ env.GIT_COMMIT }}
            ghcr.io/${{ github.repository }}/sdp-identity-service:latest

      - name: Build sdp-injector
        uses: docker/build-push-action@v6
        with:
          build-args: PROFILE=${{ env.PROFILE }}
          context: .
          file: sdp-injector/Dockerfile
          push: ${{ inputs.push }}
          tags: |
            ghcr.io/${{ github.repository }}/sdp-injector:${{ env.VERSION }}
            ghcr.io/${{ github.repository }}/sdp-injector:${{ env.VERSION }}-${{ env.GIT_COMMIT }}
            ghcr.io/${{ github.repository }}/sdp-injector:latest
