name: Build and Push Client Images

on:
  workflow_run:
    workflows: [ "Test" ]
    branches: [ "main" ]
    types:
      - completed

jobs:
  docker-client-images:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bin:
          - "sdp-dnsmasq"
          - "sdp-headless-driver"
          - "sdp-headless-service"
        client-version:
          - "5.5"
          - "6.0"
          - "6.1"
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Split version into major/minor/maintenance
        uses: jungwinter/split@v2
        id: split
        with:
          msg: ${{ matrix.client-version }}
          separator: '.'

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/${{ matrix.bin }}-Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          build-args: |
            MAJOR_VERSION=${{ steps.split.outputs._0 }}
            MINOR_VERSION=${{ steps.split.outputs._1 }}
          tags: |
            ghcr.io/${{ github.repository }}/${{ matrix.bin }}:${{ matrix.client-version }}

      - name: Tag latest image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/${{ matrix.bin }}-Dockerfile
          push: ${{ matrix.client-version == '6.1' }}
          build-args: |
            MAJOR_VERSION=${{ steps.split.outputs._0 }}
            MINOR_VERSION=${{ steps.split.outputs._1 }}
          tags: |
            ghcr.io/${{ github.repository }}/${{ matrix.bin }}:latest
