name: Build and Push Client Images

on:
  workflow_call:
    inputs:
      push:
        required: true
        type: boolean
      latest-version:
        required: true
        type: string

jobs:
  docker-build-client:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        binary:
          - "sdp-dnsmasq"
          - "sdp-headless-driver"
          - "sdp-headless-service"
        client-version:
          - "5.5"
          - "6.0"
          - "6.1"
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        if: ${{ inputs.push }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get commit short hash
        run: echo GIT_COMMIT=$(git rev-parse --short "$GITHUB_SHA") >> $GITHUB_ENV

      - name: Split version into major/minor/maintenance
        uses: jungwinter/split@v2
        id: split
        with:
          msg: ${{ matrix.client-version }}
          separator: '.'

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/${{ matrix.binary }}-Dockerfile
          push: ${{ inputs.push }}
          build-args: |
            MAJOR_VERSION=${{ steps.split.outputs._0 }}
            MINOR_VERSION=${{ steps.split.outputs._1 }}
          tags: |
            ghcr.io/${{ github.repository }}/${{ matrix.binary }}:${{ matrix.client-version }}
            ghcr.io/${{ github.repository }}/${{ matrix.binary }}:${{ matrix.client-version }}-${{ env.GIT_COMMIT }}

      - name: Tag latest image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/${{ matrix.binary }}-Dockerfile
          push: ${{ inputs.push && (matrix.client-version == inputs.latest-version) }}
          build-args: |
            MAJOR_VERSION=${{ steps.split.outputs._0 }}
            MINOR_VERSION=${{ steps.split.outputs._1 }}
          tags: |
            ghcr.io/${{ github.repository }}/${{ matrix.binary }}:latest
