name: Build and Push Injector Images

on:
  workflow_run:
    workflows: [ "Build and Push Client Images" ]
    branches: [ "main" ]
    types:
      - completed

jobs:
  docker-rust:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Read package version
        id: package-version
        run: |
          version=$(cargo metadata --format-version 1 | jq --raw-output '.packages[] | select(.name == "sdp-injector") | .version')
          echo VERSION="${version}" >> $GITHUB_ENV

      - name: Get build profile
        id: build-profile
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo PROFILE="release" >> $GITHUB_ENV
          else
            echo PROFILE="debug" >> $GITHUB_ENV
          fi

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build cached layer
        uses: docker/build-push-action@v4
        with:
          build-args: PROFILE=${{ env.PROFILE }}
          context: .
          file: docker/sdp-k8s-injector-Dockerfile
          push: false
          tags: sdp-k8s-injector-build:latest

      - name: Build sdp-device-id-service
        uses: docker/build-push-action@v4
        with:
          build-args: PROFILE=${{ env.PROFILE }}
          context: .
          file: sdp-device-id-service/Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ghcr.io/${{ github.repository }}/sdp-device-id-service:${{ env.VERSION }}
            ghcr.io/${{ github.repository }}/sdp-device-id-service:latest

      - name: Build sdp-identity-service
        uses: docker/build-push-action@v4
        with:
          build-args: PROFILE=${{ env.PROFILE }}
          context: .
          file: sdp-identity-service/Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ghcr.io/${{ github.repository }}/sdp-identity-service:${{ env.VERSION }}
            ghcr.io/${{ github.repository }}/sdp-identity-service:latest

      - name: Build sdp-injector
        uses: docker/build-push-action@v4
        with:
          build-args: PROFILE=${{ env.PROFILE }}
          context: .
          file: sdp-injector/Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ghcr.io/${{ github.repository }}/sdp-injector:${{ env.VERSION }}
            ghcr.io/${{ github.repository }}/sdp-injector:latest
