name: Dry Build Clients

on:
  pull_request:
    branches:
      - main
    paths:
      - docker/sdp-dnsmasq-Dockerfile
      - docker/sdp-headless-driver-Dockerfile
      - docker/sdp-service-Dockerfile
      - assets/*
jobs:
  dry-run-docker-client:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bin:
          - "sdp-dnsmasq"
          - "sdp-headless-driver"
          - "sdp-headless-service"
        client-version:
          - "5.5"
          - "6.0"
          - "6.1"
          - "6.2"
    steps:
      - uses: actions/checkout@v3
      - name: Split version into major/minor/maintenance
        uses: jungwinter/split@v2
        id: split
        with:
          msg: ${{ matrix.client-version }}
          separator: '.'
      - name: Dry run docker client
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/${{ matrix.bin }}-Dockerfile
          push: false
          build-args: |
            MAJOR_VERSION=${{ steps.split.outputs._0 }}
            MINOR_VERSION=${{ steps.split.outputs._1 }}
          tags: ghcr.io/${{ github.repository }}/${{ matrix.bin }}:dont-push
