name: merge

on:
  push:
    branches:
      - main

jobs:
  build-push-client:
    uses: ./.github/workflows/build-push-client.yml
    with:
      latest-version: "6.2"
      push: true

  build-push-injector:
    uses: ./.github/workflows/build-push-injector.yml
    with:
      push: true

  release-chart:
    uses: ./.github/workflows/release-chart.yml
    needs: [ build-push-client, build-push-injector ]
    with:
      push: true

  release-chart-oci:
    uses: ./.github/workflows/release-chart-oci.yml
    needs: [ build-push-client, build-push-injector ]
    with:
      push: true
