name: merge

on:
  push:
    branches:
      - main

jobs:
  build-push-client:
    uses: ./.github/workflows/build-push-client.yml
    with:
      latest-version: "6.1"
      push: true

  build-push-injector:
    uses: ./.github/workflows/build-push-injector.yml
    with:
      push: true

  release-chart:
    uses: ./.github/workflows/release-chart.yml
    with:
      secrets: inherit

  release-chart-oci:
    uses: ./.github/workflows/release-chart-oci.yml
    with:
      secrets: inherit
