name: Release Chart OCI

on:
  workflow_call:
    inputs:
      push:
        type: boolean
        required: true

jobs:
  helm-crd:
    runs-on: ubuntu-latest
    env:
      HELM_EXPERIMENTAL_OCI: 1
    steps:
      - uses: actions/checkout@v4

      - uses: mikefarah/yq@master
        id: chartVersion
        with:
          cmd: yq eval .version k8s/crd/Chart.yaml

      - uses: azure/setup-helm@v4
        with:
          version: 3.7.2

      - name: Login to GitHub Container Registry
        if: ${{ inputs.push }}
        run: helm registry login ghcr.io/${{ github.repository }} --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }}

      - name: Lint chart
        run: helm lint k8s/crd

      - name: Package chart
        run: helm package k8s/crd --dependency-update

      - name: Push chart
        if: ${{ inputs.push }}
        run: helm push sdp-k8s-injector-crd-${{ steps.chartVersion.outputs.result }}.tgz oci://ghcr.io/appgate/charts

  helm-k8s-injector:
    runs-on: ubuntu-latest
    needs:
      - helm-crd
    env:
      HELM_EXPERIMENTAL_OCI: 1
    steps:
      - uses: actions/checkout@v4
      - uses: mikefarah/yq@master
        id: chartVersion
        with:
          cmd: yq eval .version k8s/chart/Chart.yaml
      - uses: azure/setup-helm@v4
        with:
          version: 3.7.2
      - name: Login to GitHub Container Registry
        if: ${{ inputs.push }}
        run: helm registry login ghcr.io/${{ github.repository }} --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }}
      - name: Lint chart
        run: helm lint k8s/chart
      - name: Package chart
        run: helm package k8s/chart --dependency-update
      - name: Push chart
        if: ${{ inputs.push }}
        run: helm push sdp-k8s-injector-${{ steps.chartVersion.outputs.result }}.tgz oci://ghcr.io/appgate/charts
