name: Release Chart OCI

on:
  workflow_run:
    workflows: [ "Build and Push Injector Images" ]
    branches: [ "main" ]
    types:
      - completed

jobs:
  helm-crd:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    env:
      HELM_EXPERIMENTAL_OCI: 1
    steps:
      - uses: actions/checkout@v3

      - uses: mikefarah/yq@master
        id: chartVersion
        with:
          cmd: yq eval .version k8s/crd/Chart.yaml

      - uses: azure/setup-helm@v3
        with:
          version: 3.7.2

      - uses: mikefarah/yq@master
        id: thisChartVersion
        with:
          cmd: yq eval .version k8s/crd/Chart.yaml
      - name: Push?
        id: should-push
        shell: bash
        run: |
          wget --quiet https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O ./yq && chmod +x ./yq
          MASTER_CHART_VERSION=$(curl --silent https://raw.githubusercontent.com/appgate/sdp-k8s-injector/main/k8s/chart/Chart.yaml | ./yq -r .version)
          THIS_CHART_VERSION=$(./yq -r .version k8s/chart/Chart.yaml)
          echo SHOULD_PUSH="$([[ "${MASTER_CHART_VERSION}" == "${THIS_CHART_VERSION}" ]]; echo $?)" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        run: helm registry login ghcr.io/${{ github.repository }} --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }}

      - name: Lint chart
        run: helm lint k8s/crd

      - name: Package chart
        run: helm package k8s/crd --dependency-update

      - name: Push chart
        if: ${{ (github.ref == 'refs/heads/main') && (env.SHOULD_PUSH == 1) }}
        run: helm push sdp-k8s-injector-crd-${{ steps.chartVersion.outputs.result }}.tgz oci://ghcr.io/appgate/charts

  helm-k8s-injector:
    runs-on: ubuntu-latest
    needs:
      - helm-crd
    env:
      HELM_EXPERIMENTAL_OCI: 1
    steps:
      - uses: actions/checkout@v3

      - uses: mikefarah/yq@master
        id: chartVersion
        with:
          cmd: yq eval .version k8s/chart/Chart.yaml

      - uses: azure/setup-helm@v3
        with:
          version: 3.7.2

      - uses: mikefarah/yq@master
        id: thisChartVersion
        with:
          cmd: yq eval .version k8s/crd/Chart.yaml
      - name: Push?
        id: should-push
        shell: bash
        run: |
          wget --quiet https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O ./yq && chmod +x ./yq
          MASTER_CHART_VERSION=$(curl --silent https://raw.githubusercontent.com/appgate/sdp-k8s-injector/main/k8s/chart/Chart.yaml | ./yq -r .version)
          THIS_CHART_VERSION=$(./yq -r .version k8s/chart/Chart.yaml)
          echo SHOULD_PUSH="$([[ "${MASTER_CHART_VERSION}" == "${THIS_CHART_VERSION}" ]]; echo $?)" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        run: helm registry login ghcr.io/${{ github.repository }} --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }}

      - name: Lint chart
        run: helm lint k8s/chart

      - name: Package chart
        run: helm package k8s/chart --dependency-update

      - name: Push chart
        if: ${{ (github.ref == 'refs/heads/main') && (env.SHOULD_PUSH == 1) }}
        run: helm push sdp-k8s-injector-${{ steps.chartVersion.outputs.result }}.tgz oci://ghcr.io/appgate/charts
